"""add_input_hash_fields_to_stories

Revision ID: 06f5e03834a8
Revises: 7ad7c9f4ef75
Create Date: 2026-02-22 23:29:13.856068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f5e03834a8'
down_revision: Union[str, Sequence[str], None] = '7ad7c9f4ef75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planning_input_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('designing_input_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('coding_input_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('coding_input_hash')
        batch_op.drop_column('designing_input_hash')
        batch_op.drop_column('planning_input_hash')

    # ### end Alembic commands ###
