"""add label to global_capability_configs

Revision ID: 113ab53725b3
Revises: 06f5e03834a8
Create Date: 2026-02-24 00:27:34.118678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113ab53725b3'
down_revision: Union[str, Sequence[str], None] = '06f5e03834a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_capability_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_capability_configs', schema=None) as batch_op:
        batch_op.drop_column('label')

    # ### end Alembic commands ###
