"""composite_key_capability_provider

Revision ID: 48cd007eedd8
Revises: 113ab53725b3
Create Date: 2026-02-24 09:01:04.898544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '48cd007eedd8'
down_revision: Union[str, Sequence[str], None] = '113ab53725b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Fill NULL provider values before adding NOT NULL constraint
    op.execute("UPDATE global_capability_configs SET provider = '' WHERE provider IS NULL")

    with op.batch_alter_table('global_capability_configs', schema=None) as batch_op:
        batch_op.alter_column('provider',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_index(batch_op.f('capability'))
        batch_op.create_unique_constraint('uq_cap_provider', ['capability', 'provider'])
        batch_op.drop_column('label')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_capability_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('uq_cap_provider', type_='unique')
        batch_op.create_index(batch_op.f('capability'), ['capability'], unique=True)
        batch_op.alter_column('provider',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
