"""add workspace_dir to projects

Revision ID: 9a8cf012c8b8
Revises: 8165ca5c54d3
Create Date: 2026-02-16 22:45:24.560775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8cf012c8b8'
down_revision: Union[str, Sequence[str], None] = '8165ca5c54d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_dir', sa.String(length=500), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('workspace_dir')

    # ### end Alembic commands ###
