"""restore_label_column

Revision ID: 9b7ecc1b0933
Revises: 48cd007eedd8
Create Date: 2026-02-24 09:14:58.503539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b7ecc1b0933'
down_revision: Union[str, Sequence[str], None] = '48cd007eedd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_capability_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_capability_configs', schema=None) as batch_op:
        batch_op.drop_column('label')

    # ### end Alembic commands ###
