"""drop dead columns from tasks, pull_requests, skills

Revision ID: c89325769abc
Revises: 01338f5b4447
Create Date: 2026-02-24 11:05:17.251242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c89325769abc'
down_revision: Union[str, Sequence[str], None] = '01338f5b4447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.drop_column('repo_url')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_column('command')
        batch_op.drop_column('description')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('scope')
        batch_op.drop_column('repo_url')
        batch_op.drop_column('acceptance_criteria')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acceptance_criteria', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('repo_url', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('scope', mysql.TEXT(), nullable=False))

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('command', mysql.TEXT(), nullable=False))

    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repo_url', mysql.VARCHAR(length=500), nullable=False))

    # ### end Alembic commands ###
